// admin-angular/src/app/features/login/login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule],
  templateUrl: './login.component.html',
  styleUrl: './login.component.css',
})
export class LoginComponent {
  private fb = inject(FormBuilder);
  private auth = inject(AuthService);
  private router = inject(Router);

  submitting = false;
  error = '';

  form = this.fb.nonNullable.group({
    email: ['admin@isil.edu.pe', [Validators.required, Validators.email]],
    password: ['', [Validators.required, Validators.minLength(6)]],
  });

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.submitting = true;
    this.error = '';
    const { email, password } = this.form.getRawValue();

    this.auth.login(email, password).subscribe({
      next: (res) => {
        if (res.user.role !== 'admin') {
          this.error = 'Esta cuenta no tiene permisos de administrador.';
          this.auth.logout();
          this.submitting = false;
          return;
        }
        this.router.navigate(['/cursos']);
      },
      error: (err) => {
        this.error = err.error?.message || 'No se pudo iniciar sesión';
        this.submitting = false;
      },
    });
  }
}

<div class="login-wrap">
  <form class="login-card" [formGroup]="form" (ngSubmit)="submit()">
    <h1>🎓 Panel Admin</h1>
    <p class="subtitle">Plataforma de Gestión de Cursos</p>

    @if (error) {
      <div class="alert">{{ error }}</div>
    }

    <label>
      Correo
      <input type="email" formControlName="email" placeholder="admin@isil.edu.pe" />
      @if (form.controls.email.touched && form.controls.email.invalid) {
        <small class="err">Ingresa un correo válido</small>
      }
    </label>

    <label>
      Contraseña
      <input type="password" formControlName="password" />
      @if (form.controls.password.touched && form.controls.password.invalid) {
        <small class="err">Mínimo 6 caracteres</small>
      }
    </label>

    <button type="submit" [disabled]="submitting">
      {{ submitting ? 'Ingresando…' : 'Ingresar' }}
    </button>

    <p class="hint">Demo: <code>admin&#64;isil.edu.pe</code> / <code>Admin123*</code></p>
  </form>
</div>

// student-react/src/pages/Login.jsx
import { useState } from 'react';
import { useNavigate, useLocation, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext.jsx';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const from = location.state?.from || '/';

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setSubmitting(true);
    try {
      await login(email, password);
      navigate(from, { replace: true });
    } catch (err) {
      setError(err.response?.data?.message || 'No se pudo iniciar sesión');
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="container auth-wrap">
      <form className="auth-card" onSubmit={handleSubmit}>
        <h2>Iniciar sesión</h2>
        {error && <div className="alert alert-error">{error}</div>}
        <label>
          Correo
          <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required placeholder="tucorreo@isil.edu.pe" />
        </label>
        <label>
          Contraseña
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required />
        </label>
        <button className="btn btn-primary" disabled={submitting}>
          {submitting ? 'Ingresando…' : 'Ingresar'}
        </button>
        <p className="muted center">¿No tienes cuenta? <Link to="/registro">Regístrate</Link></p>
        <p className="hint">Demo estudiante: <code>estudiante@isil.edu.pe</code> / <code>Estudiante123*</code></p>
      </form>
    </div>
  );
}
